@startuml architecture

package "Kafka + KSQL" as k {
  queue blocks
  queue slots
  queue token_account_balance_changes
  queue bonding_token_account_balance_changes
  queue reserve_token_account_balance_changes
  queue token_bonding_initializes
  queue token_bonding_base_storage #fff
  queue token_bonding_target_mint #fff
  queue events
  queue token_bonding_supply_changes

    
  events --> token_bonding_initializes

  events --> token_account_balance_changes
  token_bonding_initializes --> token_bonding_target_mint
  token_bonding_target_mint --> bonding_token_account_balance_changes
  token_bonding_initializes --> token_bonding_base_storage
  token_account_balance_changes --> bonding_token_account_balance_changes
  token_account_balance_changes --> reserve_token_account_balance_changes
  token_bonding_base_storage --> reserve_token_account_balance_changes
}

agent KafkaS3BlockUploader
agent AccountLeaderboard
agent TopTokensLeaderboard
agent collectiveAPI
agent SlotIdentiier

cloud Solana
cloud S3
database Redis
person UI

Solana -> SlotIdentiier
SlotIdentiier -> slots
Solana --> KafkaS3BlockUploader
slots --> KafkaS3BlockUploader
KafkaS3BlockUploader -> blocks
KafkaS3BlockUploader -> S3

agent EventTransformer

S3 -> EventTransformer
blocks --> EventTransformer
EventTransformer -> events

TopTokensLeaderboard --> Redis

bonding_token_account_balance_changes --> AccountLeaderboard
reserve_token_account_balance_changes --> TopTokensLeaderboard
AccountLeaderboard --> Redis

Redis -> collectiveAPI

collectiveAPI -> UI
@enduml
