@startuml architecture

package "Kafka + KSQL" as k {
  queue signatures_star
  queue signatures
  queue transactions
  queue token_account_balance_changes
  queue bonding_token_account_balance_changes
  queue reserve_token_account_balance_changes
  queue token_bonding_initializes
  queue token_bonding_base_storage #fff
  queue token_bonding_target_mint #fff
  queue events
    
  events --> token_bonding_initializes

  events --> token_account_balance_changes
  token_bonding_initializes --> token_bonding_target_mint
  token_bonding_target_mint --> bonding_token_account_balance_changes
  token_bonding_initializes --> token_bonding_base_storage
  token_account_balance_changes --> bonding_token_account_balance_changes
  token_account_balance_changes --> reserve_token_account_balance_changes
  token_bonding_base_storage --> reserve_token_account_balance_changes
}

agent KafkaSignatureIdentifier
agent AccountLeaderboard
agent TopTokensLeaderboard
agent collectiveAPI
agent KafkaSignatureCollector
agent KafkaSignatureProcessor

cloud Solana
database Redis
person UI

Solana -> KafkaSignatureIdentifier
KafkaSignatureIdentifier --> signatures_star
signatures_star --> KafkaSignatureCollector
KafkaSignatureCollector -> signatures
signatures -> KafkaSignatureProcessor
KafkaSignatureProcessor --> transactions

agent EventTransformer

transactions --> EventTransformer
EventTransformer -> events

TopTokensLeaderboard --> Redis

bonding_token_account_balance_changes --> AccountLeaderboard
reserve_token_account_balance_changes --> TopTokensLeaderboard
AccountLeaderboard --> Redis

Redis -> collectiveAPI

collectiveAPI -> UI
@enduml
