version: '2'
services:
  collective-signature-identifier:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    image: data-pipelines:latest
    command: node dist/lib/kafka-signature-identifier.js
    environment:
      SOLANA_URL: "http://host.docker.internal:8899"
      KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:39092"
      KAFKA_TOPIC: json.solana.signatures.collective
      ADDRESS: TCo1sfSr2nCudbeJPykbif64rG9K1JNMGzrtzvPmp3y
    
  bonding-signature-identifier:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    image: data-pipelines:latest
    command: node dist/lib/kafka-signature-identifier.js
    environment:
      SOLANA_URL: "http://host.docker.internal:8899"
      KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:39092"
      KAFKA_TOPIC: json.solana.signatures.bonding
      ADDRESS: TBondmkCYxaPCKG4CHYfVTcwQ8on31xnJrPzk8F8WsS
    

  ksql-bootstrap-1:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: confluentinc/ksqldb-cli:0.19.0
    command: >
      bash -c "
      ksql --config-file /config/ksql-server.properties --file /ksql/0001-events.sql http://host.docker.internal:8088 &&
      ksql --config-file /config/ksql-server.properties --file /ksql/0002-users.sql http://host.docker.internal:8088 &&
      ksql --config-file /config/ksql-server.properties --file /ksql/0003-bonding-account-balance-changes.sql http://host.docker.internal:8088 && 
      ksql --config-file /config/ksql-server.properties --file /ksql/0004-reserve-account-balance-changes.sql http://host.docker.internal:8088
      "
    volumes:
      - ../ksql:/ksql
      - ./:/config

  top-token-leaderboard:
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: data-pipelines:latest
    command: node dist/lib/leaderboard
    container_name: top-token-leaderboard
    environment:
      PLUGIN: "TOP_TOKENS"
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:39092
      KAFKA_INPUT_TOPIC: json.solana.latest_reserve_token_account_balances
      KAFKA_OFFSET_RESET: earliest
      KAFKA_GROUP_ID: top-token-leaderboard
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379

  
  account-leaderboard:
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: data-pipelines:latest
    command: node dist/lib/leaderboard
    container_name: account-leaderboard
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:39092
      KAFKA_INPUT_TOPIC: json.solana.latest_bonding_token_account_balances
      KAFKA_OFFSET_RESET: earliest
      KAFKA_GROUP_ID: account-leaderboard
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379

  strata-api:
    restart: always
    ports:
      - 8083:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: strata-api:latest
    container_name: strata-api
    environment:
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      PORT: 8083


  